"""
Data models for UEBA Server.
Defines the NormalizedEvent schema, Alert schema, and related types.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from enum import Enum


class EventLevel(str, Enum):
    """Event severity levels."""
    VERBOSE = "Verbose"
    INFORMATION = "Information"
    WARNING = "Warning"
    ERROR = "Error"
    CRITICAL = "Critical"
    UNKNOWN = "Unknown"


# ============================================
# UEBA Behavior Types
# ============================================

class BehaviorType(str, Enum):
    """Known UEBA behavior detection types."""
    FAILED_LOGIN_BURST = "failed_login_burst"
    SUSPICIOUS_PATH_EXECUTION = "suspicious_path_execution"
    SECURITY_LOG_CLEARING = "security_log_clearing"
    RESTRICTED_HOURS_LOGIN = "restricted_hours_login"
    FIREWALL_DISABLED = "firewall_disabled"
    PRIVILEGE_ESCALATION = "privilege_escalation"
    UEBA_ANOMALY = "ueba_anomaly"


# Human-friendly labels for behaviors
BEHAVIOR_LABELS = {
    BehaviorType.FAILED_LOGIN_BURST: "Failed Login Burst",
    BehaviorType.SUSPICIOUS_PATH_EXECUTION: "Suspicious Path Execution",
    BehaviorType.SECURITY_LOG_CLEARING: "Security Log Clearing Attempt",
    BehaviorType.RESTRICTED_HOURS_LOGIN: "Restricted Hours Login",
    BehaviorType.FIREWALL_DISABLED: "Firewall Disabled",
    BehaviorType.PRIVILEGE_ESCALATION: "Privilege Escalation",
    BehaviorType.UEBA_ANOMALY: "UEBA Anomaly Detection",
}


# ============================================
# Alert Model
# ============================================

class Alert(BaseModel):
    """
    UEBA Alert generated by behavior detection rules.
    """
    id: Optional[int] = Field(default=None, description="Auto-incremented database ID")
    timestamp: datetime = Field(description="When the alert was generated")
    behavior: str = Field(description="Behavior rule that triggered the alert")
    risk_score: int = Field(default=50, ge=0, le=100, description="Risk score 0-100")
    
    # Alert lifecycle
    status: str = Field(default="open", description="Alert status: open/closed/acknowledged")
    first_seen: Optional[datetime] = Field(default=None, description="First occurrence timestamp")
    last_seen: Optional[datetime] = Field(default=None, description="Most recent occurrence")
    occurrence_count: int = Field(default=1, ge=1, description="Number of occurrences")
    
    # Context
    host: str = Field(default="unknown", description="Affected host")
    user: str = Field(default="unknown", description="Affected user")
    
    # Rule-specific fields (nullable based on behavior type)
    source_ip: Optional[str] = Field(default=None, description="Source IP (for login alerts)")
    fail_count: Optional[int] = Field(default=None, description="Failed login count")
    file_event_count: Optional[int] = Field(default=None, description="File events count")
    archive_process_name: Optional[str] = Field(default=None, description="Archive process name")
    target_path: Optional[str] = Field(default=None, description="Target file path")
    
    # Summary and details
    summary: str = Field(default="", description="Short summary for table display")
    details: Optional[str] = Field(default=None, description="Full JSON details")
    
    # MVP P0: Explainability and MITRE mapping
    reasons: Optional[List[Dict[str, Any]]] = Field(default=None, description="JSON array of anomaly reasons")
    mitre_tactics: Optional[List[str]] = Field(default=None, description="JSON array of MITRE tactic IDs (e.g., TA0010)")
    mitre_techniques: Optional[List[str]] = Field(default=None, description="JSON array of MITRE technique IDs (e.g., T1048)")
    evidence_event_ids: Optional[List[int]] = Field(default=None, description="JSON array of related event IDs")
    
    class Config:
        use_enum_values = True
        json_encoders = {
            datetime: lambda v: v.isoformat() if v else None
        }


class AlertResponse(BaseModel):
    """API response wrapper for alerts."""
    alerts: List[Alert]
    total_count: int
    has_more: bool


class AlertStats(BaseModel):
    """Statistics about alerts for the dashboard."""
    total_alerts: int
    alerts_last_hour: int
    alerts_last_24h: int
    unique_hosts: int
    unique_users: int
    high_risk_24h: int  # risk_score >= 80
    by_behavior: dict  # Count per behavior type


class EventCategory(str, Enum):
    """Event category for UEBA classification."""
    PROCESS = "process"
    FILE = "file"
    NETWORK = "network"
    AUTH = "auth"
    REGISTRY = "registry"
    OTHER = "other"


class EventSource(str, Enum):
    """
    Source of the event for multi-source pipeline.
    
    Identifies which log source the event came from (Windows or Linux).
    """
    SYSMON = "sysmon"
    WINDOWS_EVENT = "windows_event"
    LINUX_SYSLOG = "linux_syslog"
    LINUX_AUTH = "linux_auth"
    LINUX_JOURNAL = "linux_journal"
    LINUX_AUDIT = "linux_audit"
    UNKNOWN = "unknown"


# Human-friendly labels for event sources
SOURCE_LABELS = {
    EventSource.SYSMON: "Sysmon",
    EventSource.WINDOWS_EVENT: "Event Viewer",
    EventSource.LINUX_SYSLOG: "Linux Syslog",
    EventSource.LINUX_AUTH: "Linux Auth",
    EventSource.LINUX_JOURNAL: "Linux Journal",
    EventSource.LINUX_AUDIT: "Linux Audit",
    EventSource.UNKNOWN: "Unknown",
}


class AuthResult(str, Enum):
    """Authentication result for auth events."""
    SUCCESS = "success"
    FAILED = "failed"
    UNKNOWN = "unknown"


class NormalizedEvent(BaseModel):
    """
    Normalized event schema for UEBA system.
    
    This is the canonical representation of security events after
    normalization from various sources (Sysmon, Windows Events, etc.).
    """
    
    # Unique identifier (auto-generated)
    id: Optional[int] = Field(default=None, description="Auto-incremented database ID")
    
    # Timestamp in ISO-8601 UTC format
    timestamp: datetime = Field(description="Event timestamp in UTC")
    
    # Event source (sysmon, windows_event, etc.)
    source: EventSource = Field(default=EventSource.SYSMON, description="Event source type (sysmon, windows_event)")
    
    # Source information
    host: str = Field(default="unknown", description="Source machine name")
    user: str = Field(default="unknown", description="User account associated with event")
    
    # Event classification
    event_id: int = Field(description="Windows/Sysmon Event ID")
    level: EventLevel = Field(default=EventLevel.INFORMATION, description="Event severity level")
    provider: str = Field(default="unknown", description="Event provider name")
    category: EventCategory = Field(default=EventCategory.OTHER, description="Event category for UEBA")
    subcategory: Optional[str] = Field(default=None, description="Event subcategory (logon, failed_logon, process_create, connection, etc.)")
    
    # Process information
    process_name: Optional[str] = Field(default=None, description="Process name")
    process_id: Optional[int] = Field(default=None, description="Process ID (PID)")
    parent_process_name: Optional[str] = Field(default=None, description="Parent process name")
    parent_process_id: Optional[int] = Field(default=None, description="Parent process ID (PPID)")
    image_path: Optional[str] = Field(default=None, description="Full path to executable")
    
    # Command line (important for security analysis)
    command_line: Optional[str] = Field(default=None, description="Command line arguments")
    
    # Network information (for network events)
    source_ip: Optional[str] = Field(default=None, description="Source IP address")
    source_port: Optional[int] = Field(default=None, description="Source port")
    dest_ip: Optional[str] = Field(default=None, description="Destination IP address")
    dest_port: Optional[int] = Field(default=None, description="Destination port")
    
    # File information (for file events)
    target_filename: Optional[str] = Field(default=None, description="Target file path")
    file_hash: Optional[str] = Field(default=None, description="File hash (SHA256/MD5)")
    
    # Authentication information (for auth events - 4624/4625)
    auth_result: Optional[AuthResult] = Field(default=None, description="Auth result: success/failed")
    logon_type: Optional[int] = Field(default=None, description="Windows logon type (2=Interactive, 3=Network, etc.)")
    workstation: Optional[str] = Field(default=None, description="Source workstation name")
    failure_reason: Optional[str] = Field(default=None, description="Auth failure reason if applicable")
    
    # Event content
    message: str = Field(default="", description="Human-readable event summary")
    
    # Original data (for debugging/forensics)
    raw_json: Optional[str] = Field(default=None, description="Original raw JSON event")
    
    # Ingestion metadata
    ingested_at: datetime = Field(default_factory=datetime.utcnow, description="When event was received")
    
    # Risk assessment fields (added by AI Risk Engine)
    risk_score: Optional[float] = Field(default=None, description="AI risk score (0-100)")
    risk_level: Optional[str] = Field(default=None, description="Risk level: low/medium/high")
    rule_score: Optional[float] = Field(default=None, description="Rule-based component score")
    anomaly_score: Optional[float] = Field(default=None, description="Anomaly detection component score")
    context_score: Optional[float] = Field(default=None, description="Context/embedding component score")
    
    # Maximum telemetry fields (for comprehensive UEBA)
    channel: Optional[str] = Field(default=None, description="Windows Event Log channel name")
    record_id: Optional[int] = Field(default=None, description="Windows Event RecordId")
    user_sid: Optional[str] = Field(default=None, description="User SID if available")
    logon_id: Optional[str] = Field(default=None, description="Logon ID for session tracking")
    action_type: Optional[str] = Field(default=None, description="Derived action type (lock, unlock, logon, logoff, ps_scriptblock, defender_alert, firewall_change, task_created, wmi_exec, usb_insert, rdp_connect, etc.)")
    task: Optional[int] = Field(default=None, description="Windows Event Task")
    keywords: Optional[str] = Field(default=None, description="Windows Event Keywords")
    
    # Sysmon-specific fields for ProcessAccess (ID 10) and CreateRemoteThread (ID 8)
    source_image: Optional[str] = Field(default=None, description="Sysmon: Source process image path")
    target_image: Optional[str] = Field(default=None, description="Sysmon: Target process image path")
    granted_access: Optional[str] = Field(default=None, description="Sysmon ID 10: Access rights granted (hex)")
    call_trace: Optional[str] = Field(default=None, description="Sysmon ID 10: Call stack trace")
    start_address: Optional[str] = Field(default=None, description="Sysmon ID 8: Thread start address")
    start_module: Optional[str] = Field(default=None, description="Sysmon ID 8: Module containing start address")
    start_function: Optional[str] = Field(default=None, description="Sysmon ID 8: Function at start address")
    new_thread_id: Optional[int] = Field(default=None, description="Sysmon ID 8: New thread ID")
    
    # Registry fields for Sysmon ID 12/13/14
    target_object: Optional[str] = Field(default=None, description="Sysmon: Registry key/value path")
    registry_details: Optional[str] = Field(default=None, description="Sysmon ID 13: Registry value data")
    
    # Service fields for System 7045 / Security 4697
    service_name: Optional[str] = Field(default=None, description="Service name for service events")
    service_file_name: Optional[str] = Field(default=None, description="Service executable path")
    service_type: Optional[str] = Field(default=None, description="Service type")
    service_start_type: Optional[str] = Field(default=None, description="Service start type")
    
    # Scheduled task fields for Security 4698
    task_name: Optional[str] = Field(default=None, description="Scheduled task name")
    task_content: Optional[str] = Field(default=None, description="Scheduled task XML content")
    
    # Share access fields for Security 5140/5145
    share_name: Optional[str] = Field(default=None, description="Network share name")
    share_path: Optional[str] = Field(default=None, description="Network share local path")
    relative_target_name: Optional[str] = Field(default=None, description="File accessed on share")
    
    # Kerberos fields for Security 4769
    ticket_encryption_type: Optional[str] = Field(default=None, description="Kerberos ticket encryption type")
    ticket_options: Optional[str] = Field(default=None, description="Kerberos ticket options")
    service_sid: Optional[str] = Field(default=None, description="Service SID for Kerberos")

    # ============================================
    # Field Presence Helper Methods (Null-Safety)
    # ============================================
    
    def has_command_line(self) -> bool:
        """Check if command_line field is present and non-empty."""
        return self.command_line is not None and len(self.command_line.strip()) > 0
    
    def has_process_hierarchy(self) -> bool:
        """Check if process hierarchy fields are present (PID and PPID)."""
        return self.process_id is not None and self.parent_process_id is not None
    
    def has_network_context(self) -> bool:
        """Check if network fields are present (source or dest IP/port)."""
        return (self.source_ip is not None or self.dest_ip is not None or 
                self.source_port is not None or self.dest_port is not None)
    
    def has_file_hash(self) -> bool:
        """Check if file hash is present and non-empty."""
        return self.file_hash is not None and len(self.file_hash.strip()) > 0
    
    def has_auth_info(self) -> bool:
        """Check if authentication result is present."""
        return self.auth_result is not None

    class Config:
        """Pydantic configuration."""
        use_enum_values = True
        json_encoders = {
            datetime: lambda v: v.isoformat() if v else None
        }


class EventResponse(BaseModel):
    """API response wrapper for events."""
    events: list[NormalizedEvent]
    total_count: int
    has_more: bool


class EventStats(BaseModel):
    """Statistics about stored events."""
    total_events: int
    events_last_hour: int
    events_last_day: int
    unique_hosts: int
    unique_users: int
    error_count: int
    warning_count: int
    # Source breakdown
    by_source: dict = Field(default_factory=dict, description="Event counts per source")

