"""
Behavior Detection Orchestrator.

Coordinates all behavior detection modules and runs them against
incoming events. Provides a unified interface for the ingest pipeline.
"""

import logging
from typing import List, Callable, Optional

from ..models import NormalizedEvent, Alert
from .suspicious_path_execution import detect_suspicious_path_execution
from .security_log_clearing import detect_security_log_clearing
from .failed_login_burst import detect_failed_login_burst
from .restricted_hours_login import detect_restricted_hours_login
from .firewall_disabled import detect_firewall_disabled
from .privilege_escalation import detect_privilege_escalation

logger = logging.getLogger(__name__)

# Type alias for detector functions
DetectorFunc = Callable[[NormalizedEvent, Optional[object], Optional[dict]], List[Alert]]


class BehaviorOrchestrator:
    """
    Orchestrates all behavior detection modules.
    
    Provides a single entry point for running all detectors against
    incoming events and collecting generated alerts.
    """
    
    def __init__(self, config: dict = None):
        """
        Initialize the orchestrator.
        
        Args:
            config: Configuration dictionary with settings per detector
        """
        self.config = config or {}
        self._detectors: List[tuple[str, DetectorFunc]] = []
        
        # Register all built-in detectors
        self._register_builtin_detectors()
    
    def _register_builtin_detectors(self):
        """Register all built-in behavior detectors."""
        # Failed login burst (auth events)
        self.register_detector(
            "failed_login_burst",
            detect_failed_login_burst
        )
        
        # Suspicious path execution (Sysmon process events)
        self.register_detector(
            "suspicious_path_execution",
            detect_suspicious_path_execution
        )
        
        # Security log clearing attempts (Sysmon process events)
        self.register_detector(
            "security_log_clearing",
            detect_security_log_clearing
        )
        
        # Restricted hours login (auth events - 13:00-20:00)
        self.register_detector(
            "restricted_hours_login",
            detect_restricted_hours_login
        )
        
        # Firewall disabled (Windows Firewall event 5025)
        self.register_detector(
            "firewall_disabled",
            detect_firewall_disabled
        )
        
        # Privilege escalation (Security events 4728, 4732, 4756)
        self.register_detector(
            "privilege_escalation",
            detect_privilege_escalation
        )
        
        logger.info(f"Registered {len(self._detectors)} behavior detectors")
    
    def register_detector(self, name: str, detector: DetectorFunc):
        """
        Register a new behavior detector.
        
        Args:
            name: Unique name for the detector
            detector: Detection function
        """
        self._detectors.append((name, detector))
        logger.debug(f"Registered detector: {name}")
    
    def run_detectors(
        self,
        event: NormalizedEvent,
        db=None,
        config: dict = None
    ) -> List[Alert]:
        """
        Run all registered detectors against an event.
        
        Args:
            event: Normalized event to analyze
            db: Database connection for detectors that need historical data
            config: Runtime configuration overrides
            
        Returns:
            List of all alerts generated by all detectors
        """
        all_alerts = []
        merged_config = {**self.config, **(config or {})}
        
        # Debug: log event being processed (only for Sysmon events)
        if event.provider and "Sysmon" in event.provider:
            logger.debug(
                f"Processing Sysmon event: id={event.event_id}, "
                f"process={event.process_name}, user={event.user}, "
                f"has_cmd={bool(event.command_line)}"
            )
        
        for name, detector in self._detectors:
            try:
                # Get detector-specific config if available
                detector_config = merged_config.get(name, {})
                
                alerts = detector(event, db, detector_config)
                
                if alerts:
                    logger.info(f"Detector '{name}' generated {len(alerts)} alert(s) for event_id={event.event_id}")
                    all_alerts.extend(alerts)
                    
            except Exception as e:
                logger.exception(f"Error in detector '{name}': {e}")
                # Continue with other detectors even if one fails
                continue
        
        return all_alerts
    
    @property
    def detector_names(self) -> List[str]:
        """Get list of registered detector names."""
        return [name for name, _ in self._detectors]


# Global orchestrator instance
_orchestrator: Optional[BehaviorOrchestrator] = None


def get_orchestrator() -> BehaviorOrchestrator:
    """Get or create the global orchestrator instance."""
    global _orchestrator
    if _orchestrator is None:
        _orchestrator = BehaviorOrchestrator()
    return _orchestrator


def run_all_detectors(
    event: NormalizedEvent,
    db=None,
    config: dict = None
) -> List[Alert]:
    """
    Convenience function to run all detectors against an event.
    
    This is the main entry point used by the ingest pipeline.
    
    Args:
        event: Normalized event to analyze
        db: Database connection
        config: Runtime configuration
        
    Returns:
        List of all generated alerts
    """
    orchestrator = get_orchestrator()
    return orchestrator.run_detectors(event, db, config)

